public/locales/en/common.json
public/locales/en/password-reset.json
public/locales/pl/common.json
public/locales/pl/password-reset.json
src/components/forms/forgot-password.tsx
src/components/forms/reset-password.tsx
src/lib/auth.ts
src/pages/_app.tsx
src/pages/forgot-password.tsx
src/pages/password-reset/[code].tsx
src/pages/password-reset/[token].tsx
src/types/auth.ts

[SCOUT-4](https://playmakerpro.atlassian.net/browse/SCOUT-4)
- add `forgot-password` page & form ui, handle form submission
- add `reset-password` page & form ui, handle form submission

[SCOUT-4] reset password flow

---

src/modules/auth/hooks.ts

fix: clear query cache on logout

---

src/components/nav/nav-list.tsx
src/modules/regions/details-card.tsx
src/pages/countries/[id].tsx
src/pages/countries/create.tsx
src/pages/countries/edit/[id].tsx
src/pages/countries/index.tsx

- switched to withSessionSsrRole and CardItemBasic helpers
- added regions to admin panel nav

after prs update

---

src/modules/competition-age-categories/forms/filter.tsx
src/modules/competition-age-categories/table/table.tsx
src/modules/competition-age-categories/types.ts
src/pages/competition-age-categories/index.tsx

[SCOUT-93](https://playmakerpro.atlassian.net/browse/SCOUT-93?atlOrigin=eyJpIjoiMjAzZTg3YzliMzQ1NDVlNmEyMDYwMzRlODdlZjQyNTIiLCJwIjoiaiJ9)
adjust competition age categories
- sorting, filters, fixes

adjust competition age categories

---

public/locales/en/common.json
public/locales/en/report-skill-assessment-categories.json
public/locales/pl/common.json
public/locales/pl/report-skill-assessment-categories.json
src/components/icons/index.ts
src/components/nav/nav-list.tsx
src/modules/report-skill-assessment-categories/details-card.tsx
src/modules/report-skill-assessment-categories/forms/create.tsx
src/modules/report-skill-assessment-categories/forms/edit.tsx
src/modules/report-skill-assessment-categories/forms/filter.tsx
src/modules/report-skill-assessment-categories/forms/utils.ts
src/modules/report-skill-assessment-categories/hooks.ts
src/modules/report-skill-assessment-categories/table/report-skill-assessment-categories-row.tsx
src/modules/report-skill-assessment-categories/table/report-skill-assessment-categories.tsx
src/modules/report-skill-assessment-categories/types.ts
src/modules/report-skill-assessment-categories/utils.ts
src/pages/report-skill-assessment-categories/[id].tsx
src/pages/report-skill-assessment-categories/create.tsx
src/pages/report-skill-assessment-categories/edit/[id].tsx
src/pages/report-skill-assessment-categories/index.tsx
src/services/api/methods/report-skill-assessment-categories.ts
src/services/api/modules.ts
src/types/generated.d.ts
src/utils/get-edit-data-to-submit.ts
src/utils/routes.ts

[SCOUT-32](https://playmakerpro.atlassian.net/browse/SCOUT-32)

[SCOUT-32] report skill assessment categories module

---

src/modules/seasons/forms/filter.tsx
src/modules/seasons/hooks.ts
src/modules/seasons/table/table.tsx
src/modules/seasons/types.ts
src/pages/seasons/index.tsx
src/services/api/methods/seasons.ts

[SCOUT-91](https://playmakerpro.atlassian.net/browse/SCOUT-91?atlOrigin=eyJpIjoiM2E1NzUwZjM0MTlmNDVjZGI0N2U0MDJhY2RmOGFiNzAiLCJwIjoiaiJ9)
adjusted seasons to use proper endpoint

feat: adjusted seasons

---

.eslintrc.json
package.json
src/pages/api/hello.ts
src/pages/competition-age-categories/create.tsx
src/pages/competition-groups/create.tsx
src/pages/competition-junior-levels/edit/[id].tsx
src/pages/competition-types/create.tsx
src/pages/competitions/create.tsx
src/pages/countries/create.tsx
src/pages/orders/create.tsx
src/pages/organizations/[id]/add-members.tsx
src/pages/organizations/[id]/index.tsx
src/pages/organizations/create.tsx
src/pages/organizations/edit/[id].tsx
src/pages/organizations/index.tsx
src/pages/player-positions/create.tsx
src/pages/players/[slug].tsx
src/pages/regions/create.tsx
src/pages/report-skill-assessment-templates/create.tsx
src/pages/seasons/create.tsx
src/pages/teams/[slug].tsx
src/pages/user-football-roles/create.tsx
src/pages/user-subscriptions/[id].tsx
src/pages/user-subscriptions/create.tsx
src/pages/user-subscriptions/edit/[id].tsx
src/pages/user-subscriptions/index.tsx
src/pages/users/index.tsx
yarn.lock

- fix prettier config (add eslint integration)
- fix some of linting errors

Chore: prettier config

---

.github/workflows/pr-workflow.yml

ci: add pr workflow

---

.github/workflows/pr-workflow.yml

ci: fix pr worfklow

---

src/modules/players/details-card.tsx

[SCOUT-181](https://playmakerpro.atlassian.net/browse/SCOUT-181)
Fix error with no current team for player case

[SCOUT-181] players page in case there's no current team

---

src/modules/competition-groups/forms/filter.tsx
src/modules/competition-participations/forms/filter.tsx
src/modules/competitions/forms/filter.tsx
src/modules/countries/forms/filter.tsx
src/modules/insider-notes/forms/filter.tsx
src/modules/matches/forms/filter.tsx
src/modules/notes/forms/filter.tsx
src/modules/orders/forms/filter.tsx
src/modules/organization-subscriptions/forms/filter.tsx
src/modules/players/forms/filter.tsx
src/modules/regions/forms/filter.tsx
src/modules/report-skill-assessment-templates/forms/filter.tsx
src/modules/reports/forms/filter.tsx
src/modules/team-affiliations/forms/filter.tsx
src/modules/teams/forms/filter.tsx
src/modules/user-subscriptions/forms/filter.tsx
src/modules/users/forms/filter.tsx

[SCOUT-199](https://playmakerpro.atlassian.net/browse/SCOUT-199?atlOrigin=eyJpIjoiZDY3MTQxYmQ1YjE5NDk4Mjk3OWY5YTRhNjJkN2U5NjAiLCJwIjoiaiJ9)
- changes field sizes to small on players filter form
I tried fixing footed select text issue but idk what's happening

feat: change sizes to small

---

src/components/nav/styles.ts

[SCOUT-198](https://playmakerpro.atlassian.net/browse/SCOUT-198?atlOrigin=eyJpIjoiZDI5M2M5ODM3MjZlNGUyMGFjOTFmNzRlZWE4ZTEzNTYiLCJwIjoiaiJ9)
- fixed sidebar sizing
you've said something about content margin but what about just this solution

feat: fix sidebar

---

src/components/likedTableCell/likedTableCell.tsx
src/modules/insider-notes/table/row.tsx
src/modules/insider-notes/table/table.tsx
src/modules/notes/table/row.tsx
src/modules/notes/table/table.tsx
src/modules/players/table/row.tsx
src/modules/players/table/table.tsx
src/modules/reports/table/row.tsx
src/modules/reports/table/table.tsx
src/modules/teams/table/teams-row.tsx
src/modules/teams/table/teams.tsx

[SCOUT-188](https://playmakerpro.atlassian.net/browse/SCOUT-188?atlOrigin=eyJpIjoiZmY5MzdhMGY0Zjc5NDlkYWIzMmE1OTA4MTQ5OTRiOTIiLCJwIjoiaiJ9)
- added favoutrite btn directly to players table
empty table head in order to keep fairly small width

feat: add favourite toggle to table

---

src/components/rating-range-select/rating-range-select.tsx
src/modules/notes/forms/filter.tsx
src/modules/notes/types.ts
src/modules/notes/utils.ts
src/modules/reports/types.ts
src/pages/notes/index.tsx
src/types/rating-range.ts
src/utils/rating-range-maps.ts

[SCOUT-113](https://playmakerpro.atlassian.net/browse/SCOUT-113)

[SCOUT-113] adjust rating range filter handler for notes module

---

.eslintrc.json
src/modules/reports/details.tsx
src/modules/reports/forms/components/basic-details-card.tsx
src/modules/reports/forms/edit.tsx
src/modules/reports/forms/utils.ts
src/types/generated.d.ts

[SCOUT-211](https://playmakerpro.atlassian.net/browse/SCOUT-211)

[SCOUT-211] adjust type changes

---

src/pages/dashboard.tsx

[SCOUT-207](https://playmakerpro.atlassian.net/browse/SCOUT-207?atlOrigin=eyJpIjoiODliY2UxYjgwNzhjNDJkYzhkYzZhNzBkMjhmZmI5N2EiLCJwIjoiaiJ9)
- changed fetched data limit from 2 to 1 on dashboard
note: seeding database is broken

feat: change limit to 1

---

src/modules/orders/details-card.tsx

[SCOUT-235](https://playmakerpro.atlassian.net/browse/SCOUT-235?atlOrigin=eyJpIjoiYjY5OTEyM2ZjMzUwNGU0Y2E4ZTk2M2ZlNzVlYjI3NmUiLCJwIjoiaiJ9)
- fixed error when a player isn't in a team

fix: handle no team

---

src/modules/organization-subscriptions/forms/utils.ts
src/modules/user-subscriptions/forms/utils.ts

[SCOUT-287](https://playmakerpro.atlassian.net/browse/SCOUT-287?atlOrigin=eyJpIjoiNDViMzE1NGE1MDQ1NDcxZGE2ZTQ4YjEzMDg3Y2E1MmEiLCJwIjoiaiJ9)
- make competition groups optional in subscriptions

make comp groups optional

---

src/modules/notes/forms/create.tsx
src/modules/reports/forms/create.tsx
src/pages/notes/create.tsx
src/pages/reports/create.tsx
src/utils/hooks/use-confirm-leave.ts

[SCOUT-280](https://playmakerpro.atlassian.net/browse/SCOUT-280?atlOrigin=eyJpIjoiMThlYzBiN2ZjODk4NGZhZDlhOWM0OTA2MzI2ZjcyOTQiLCJwIjoiaiJ9)
- now prompt is activated after you've clicked any form field

update confirm on leave

---

src/modules/players/table/table.tsx

[SCOUT-292](https://playmakerpro.atlassian.net/browse/SCOUT-292?atlOrigin=eyJpIjoiYmI3MjlhYjk0YzM1NDI0Y2FmZjQxY2M3MmI3YTEyZmUiLCJwIjoiaiJ9)
disabled footed sorting in players table

disable footed sort

---

src/components/details-card/details-card-item.tsx
src/modules/clubs/details-card.tsx
src/modules/matches/details-card.tsx
src/modules/players/details-card.tsx

[SCOUT-398](https://playmakerpro.atlassian.net/browse/SCOUT-398?atlOrigin=eyJpIjoiZjcwZTg2OTkwNTc4NGNjZTgzNDllMDkwMTVhZTQ1MmQiLCJwIjoiaiJ9)
- open outside links in new card - players, match, clubs

links in new card

---

src/modules/dashboard/CountCard.tsx
src/modules/dashboard/layouts/base.tsx
src/modules/dashboard/layouts/scout-organization.tsx

[SCOUT-391](https://playmakerpro.atlassian.net/browse/SCOUT-391)
-  update dashboard

visual changes

---

.github/PULL_REQUEST_TEMPLATE.md

- added scout link to pr template

add scout link

---

src/pages/_app.tsx
src/styles/fix-print.css

[SCOUT-401](https://playmakerpro.atlassian.net/browse/SCOUT-401)
- fixed printing report generating pdf with ~ 600 pages

fix print report

---

src/modules/insider-notes/details-card.tsx
src/modules/insider-notes/table/row.tsx
src/modules/notes/details-card.tsx
src/modules/notes/table/row.tsx
src/modules/reports/forms/components/basic-details-card.tsx
src/modules/reports/table/row.tsx
src/modules/users/utils.ts
src/types/generated.d.ts

[SCOUT-278](https://playmakerpro.atlassian.net/browse/SCOUT-278)
Display scout rating next to authors' name in
- reports module (table row & details)
- notes module (table row & details)
- insider notes module (table row & details)

[SCOUT-278] scout rating

---

src/modules/matches/forms/create.tsx
src/modules/matches/forms/edit.tsx
src/modules/matches/utils.ts

[SCOUT-424](https://playmakerpro.atlassian.net/browse/SCOUT-424)
- fixed handling 0 goals in match

fix 0 goals

---

src/utils/hooks/use-confirm-leave.ts

[SCOUT-437](https://playmakerpro.atlassian.net/browse/SCOUT-437)
- fixed promp showing after adding new observation

disable when not touched again

---

src/pages/players/[slug].tsx

[SCOUT-439](https://playmakerpro.atlassian.net/browse/SCOUT-439)
added missing counts to tabs on player profile

add counts to tabs

---

src/pages/teams/[slug].tsx

[SCOUT-458](https://playmakerpro.atlassian.net/browse/SCOUT-458)
- fixed not showing all players on team page

fix not showing all players

---

src/modules/notes/table/row.tsx
src/modules/notes/utils.ts
src/modules/reports/table/row.tsx
src/modules/reports/utils.ts
src/pages/notes/[id].tsx
src/pages/reports/[id]/index.tsx
src/pages/reports/[id]/print.tsx

[SCOUT-396](https://playmakerpro.atlassian.net/browse/SCOUT-396)
- more descriptive observations links

feat: more describing links

---

src/components/breadcrumbs/utils.ts

[SCOUT-396](https://playmakerpro.atlassian.net/browse/SCOUT-396)
- remove id from breadcrumbs when on detailed note/report page

remove ids in detailed notes&reports

---

src/modules/players/table/table.tsx

[SCOUT-463](https://playmakerpro.atlassian.net/browse/SCOUT-463)
- disable team sort in players table

disable team sort

---

src/modules/players/forms/filter.tsx

[SCOUT-446](https://playmakerpro.atlassian.net/browse/SCOUT-446)
- in players filter overwrite min,max rating filters when out of range 1-4

overwrite rating filter when out of rangr

---

src/modules/reports/forms/create.tsx
src/pages/reports/create.tsx

[SCOUT-464](https://playmakerpro.atlassian.net/browse/SCOUT-464)
- removed step 8 from creating report

remove step 8 from create report

---

src/pages/players/[slug].tsx

[SCOUT-471](https://playmakerpro.atlassian.net/browse/SCOUT-471)
- on player page sort observations on default by createdAt

sort observations by createdAt

---

public/locales/en/player-positions.json
public/locales/pl/player-positions.json
src/modules/player-positions/forms/create.tsx
src/modules/player-positions/forms/edit.tsx
src/modules/player-positions/forms/utils.ts
src/modules/player-positions/table/row.tsx
src/modules/player-positions/table/table.tsx
src/types/generated.d.ts

[SCOUT-465](https://playmakerpro.atlassian.net/browse/SCOUT-465)
- added player positions list order

feat: player positions list order

---

src/modules/players/forms/edit.tsx

[SCOUT-470](https://playmakerpro.atlassian.net/browse/SCOUT-470)
can now remove player role from player

fix: can remove player role

---

public/locales/en/common.json
public/locales/pl/common.json
src/modules/players/details-card.tsx
src/modules/players/forms/fields.tsx
src/modules/players/forms/utils.ts
src/types/generated.d.ts

[SCOUT-473](https://playmakerpro.atlassian.net/browse/SCOUT-473)
- add inStat url to player

player add inStat url

---

src/components/error/error-content.tsx

[SCOUT-474](https://playmakerpro.atlassian.net/browse/SCOUT-474)
- 401 error page link now points to the contatct form

add link to form on 401

---

src/modules/landing-home/CtaButton.tsx

[SCOUT-370](https://playmakerpro.atlassian.net/browse/SCOUT-370)
- can now open landing home link in new tab

make possible to open in new tab

---

src/modules/player-roles/GroupedPlayerRoleExamples.tsx
src/modules/player-roles/details-card.tsx
src/modules/player-roles/table/row.tsx
src/modules/player-roles/table/table.tsx
src/modules/player-roles/utils.ts

[SCOUT-469](https://playmakerpro.atlassian.net/browse/SCOUT-469)
- updated player roles ui

update player roles

---

src/pages/players/[slug].tsx

[SCOUT-472](https://playmakerpro.atlassian.net/browse/SCOUT-472)
- on single player page add actions to reports table

add actions to reports table

---

src/components/landing/ContactForm.tsx
src/components/landing/hooks.ts
src/components/landing/types.ts
src/modules/landing-home/hooks.ts
src/pages/club-scouting.tsx
src/pages/data-analysis.tsx
src/services/api/methods/landing.ts
src/types/generated.d.ts

[SCOUT-491](https://playmakerpro.atlassian.net/browse/SCOUT-491)
- now contact form on landing pages actually works
related backend pr required

feat: working landing form

---

src/pages/players/[slug].tsx

[SCOUT-476](https://playmakerpro.atlassian.net/browse/SCOUT-476)
- changes tabs count in single player page

change tabs count

---

src/modules/auth/hooks.ts
src/pages/login.tsx
src/utils/redirect-to-login.ts
src/utils/withSessionSsrRole.ts

[SCOUT-466](https://playmakerpro.atlassian.net/browse/SCOUT-466)
- now can redirect to original url after succesfull login

feat redirect on login

---

src/modules/players/generate-observations-info.tsx

[SCOUT-474](https://playmakerpro.atlassian.net/browse/SCOUT-474)
- in player observations info change link to club scouting contact form

change link to club scouting

---

src/modules/players/forms/edit.tsx

[SCOUT-510](https://playmakerpro.atlassian.net/browse/SCOUT-510)
- handle edit player set empty fields

handle set empty fields

---

.github/CODEOWNERS
src/modules/reports/forms/components/basic-details-card.tsx

[SCOUT-516](https://playmakerpro.atlassian.net/browse/SCOUT-516)
- hide report status

hide status

---

src/modules/reports/PrinteableReport.tsx

[SCOUT-520](https://playmakerpro.atlassian.net/browse/SCOUT-520)
- correct match score display on print

correct match score condition

---

src/modules/reports/PrinteableReport.tsx
src/modules/reports/details.tsx
src/modules/reports/forms/components/skill-assessments-card.tsx
src/modules/reports/utils.ts
src/pages/reports/[id]/index.tsx
src/pages/reports/[id]/print.tsx
src/types/generated.d.ts

[SCOUT-519](https://playmakerpro.atlassian.net/browse/SCOUT-519)
- add skills order

add skills order

---

src/modules/reports/forms/edit.tsx
src/pages/reports/edit/[id].tsx

[SCOUT-515](https://playmakerpro.atlassian.net/browse/SCOUT-515)
- add more edit options to report

add more edit fields to report

---

src/modules/matches/details-card.tsx
src/modules/notes/details-card.tsx
src/modules/players/details-card.tsx
src/modules/reports/forms/components/basic-details-card.tsx

[SCOUT-530](https://playmakerpro.atlassian.net/browse/SCOUT-530)
add edit buttons

add edit buttons

---

public/locales/en/notes.json
public/locales/pl/notes.json
src/components/combo/basicCombo.tsx
src/modules/notes/forms/create.tsx
src/modules/notes/hooks.ts
src/modules/notes/types.ts
src/pages/notes/create.tsx
src/services/api/methods/notes.ts
src/utils/hooks/api/use-list.ts

[SCOUT-525](https://playmakerpro.atlassian.net/browse/SCOUT-525)
add qucik note edit

add quick note edit

---

public/locales/en/common.json
public/locales/pl/common.json
src/components/topbar/Topbar.tsx
src/components/topbar/styles.ts
src/modules/organizations/details-card.tsx
src/modules/organizations/forms/create.tsx
src/modules/organizations/forms/edit.tsx
src/modules/organizations/forms/utils.ts
src/modules/organizations/hooks.ts
src/types/generated.d.ts

[SCOUT-508](https://playmakerpro.atlassian.net/browse/SCOUT-508)
- added organization logo

add organization logo

---

src/modules/reports/utils.ts

[SCOUT-521](https://playmakerpro.atlassian.net/browse/SCOUT-521)
- corrected id

correct compact category id

---

src/components/tables/header.tsx
src/modules/matches/table/table.tsx
src/modules/notes/table/table.tsx
src/modules/orders/table/table.tsx
src/modules/players/table/table.tsx
src/modules/reports/table/table.tsx
src/modules/teams/table/teams.tsx
src/types/tables.ts

[SCOUT-536](https://playmakerpro.atlassian.net/browse/SCOUT-536)
- more checked sortby

more checked sortby

---

src/components/tables/header.tsx
src/modules/matches/table/table.tsx
src/modules/notes/table/table.tsx
src/modules/orders/table/table.tsx
src/modules/players/table/table.tsx
src/modules/reports/table/table.tsx
src/modules/teams/table/teams.tsx
src/types/tables.ts

Release 1.4.2

---

public/locales/en/players.json
public/locales/pl/players.json
src/modules/players/forms/filter.tsx
src/modules/players/table/row.tsx
src/modules/players/table/table.tsx
src/modules/players/types.ts
src/modules/players/utils.ts
src/pages/players/index.tsx
src/types/generated.d.ts

[SCOUT-533](https://playmakerpro.atlassian.net/browse/SCOUT-533)

implement player recent avg rating

---

src/modules/notes/forms/edit.tsx

[SCOUT-541](https://playmakerpro.atlassian.net/browse/SCOUT-541)

disable submitting

---

src/modules/matches/utils.ts
src/modules/notes/details-card.tsx
src/modules/notes/table/row.tsx
src/modules/orders/table/row.tsx
src/modules/orders/utils.ts
src/modules/player-stats/details-card.tsx
src/modules/player-stats/table/row.tsx
src/modules/reports/forms/components/basic-details-card.tsx
src/modules/reports/table/row.tsx
src/pages/matches/[id].tsx
src/pages/matches/edit/[id].tsx

[SCOUT-545](https://playmakerpro.atlassian.net/browse/SCOUT-545)
- add match date to label

add match date to label

---

src/modules/player-grades/details-card.tsx
src/modules/player-grades/forms/create.tsx
src/modules/player-grades/forms/edit.tsx
src/modules/player-grades/forms/utils.ts
src/modules/player-grades/table/row.tsx
src/pages/player-grades/create.tsx
src/pages/player-grades/edit/[id].tsx
src/types/generated.d.ts

[SCOUT-537](https://playmakerpro.atlassian.net/browse/SCOUT-537)

hide competition from player grade forms

---

package.json
src/components/combo/basicCombo.tsx
src/components/combo/combo.tsx
src/utils/normalize-string.ts
yarn.lock

[SCOUT-538](https://playmakerpro.atlassian.net/browse/SCOUT-538)

combo unaaccent search

---

src/modules/players/forms/filter.tsx

hide last avg rating filter

---

src/modules/players/forms/filter.tsx

Release 1.5.1

---

src/components/combo/combo.tsx
src/modules/players/forms/filter.tsx
src/modules/players/utils.ts

[SCOUT-533](https://playmakerpro.atlassian.net/browse/SCOUT-533)
corrected filter & brought it back

correct recent avg rating filter

---

public/locales/en/reports.json
public/locales/pl/reports.json
src/modules/reports/forms/components/meta-step.tsx
src/modules/reports/forms/components/player-step.tsx
src/modules/reports/forms/create.tsx
src/modules/reports/forms/edit.tsx
src/pages/reports/create.tsx

[SCOUT-559](https://playmakerpro.atlassian.net/browse/SCOUT-559)
add player positon in create report

add player position to report create
